---
spring:
  application:
    name: ifood-service-restaurant
server:
  port: 8083
 
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    
jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:ifoodDb;DB_CLOSE_DELAY=-1
 
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create    